### ISSUE TITLE
Astro DB build fails with Cloudflare adapter

### ISSUE THREAD

**Issue by casungo** [withastro/astro#10668]
### Astro Info

```block
Astro                    v4.5.15
Node                     v20.7.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

I am logged into Astro Studio, linked, and able to work with production data using the --remote flag in dev mode.
When attempting to build with the --remote flag, I get the following error:

> [ERROR] [vite] x Build failed in 1.30s
> [commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "url" imported from "node_modules\.pnpm\@astrojs+db@0.10.0\node_modules\@astrojs\db\dist\runtime\index.js". Consider disabling ssr.noExternal or remove the built-in dependency.

### What's the expected result?

`astro build --remote` should build using the remote data.

(forked the minimal reproducible example from #10617 since the issue is in the db integration)

(for the minimal reproducible example to work you would need to download the project, login, link and then execute a build with the remote flag)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6icpvd-oyrvsw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aklevecz** [comment]
I'm having the same issue.

I tried updating my config to include: `  vite: {
    ssr: {
      noExternal: ["@astrojs/db"]
    }
  }`, but it still fails with the same message

**Comment by aklevecz** [comment]
Running into this same issue. Appreciate the urgency!

**Comment by matthewp** [comment]
I'm not seeing the issue here. Will try on my Windows computer to make sure it's not specific to Windows.

Could you try force reinstalling? Maybe something didn't get installed correctly.

**Comment by aklevecz** [comment]
For myself I was able to successfully build and deploy once I drank more coffee and realized that I'm using the Cloudflare adapter, and followed the docs on [Node compatability](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility) to enable the Node `url` library.

My config looks like this now:
```
import { defineConfig } from "astro/config";
import cloudflare from "@astrojs/cloudflare";

import db from "@astrojs/db";

export default defineConfig({
  output: "server",
  adapter: cloudflare({
    platformProxy: {
      enabled: true
    }
  }),
  integrations: [db()],
  vite: {
    ssr: {
      external: ["url"]
    }
  }
});
```

**Comment by matthewp** [comment]
@aklevecz Yeah the service is unfortunately not yet compatible with Cloudflare out of the box. Hoping to work with @alexanderniebuhr to fix that soon.

**Comment by matthewp** [comment]
@casungo are you also using Cloudflare adapter?

**Comment by casungo** [comment]
> @casungo are you also using Cloudflare adapter?

yep, idk why the astro info didn't pick that up

**Comment by matthewp** [comment]
@casungo cool, does the config @aklevecz help in your case?

**Comment by serdar** [comment]
Unfortunately I'm getting `Cannot create a remote client: missing app token.` reintroduced when it was fixed with this ticket (https://github.com/withastro/astro/issues/10617):

Subset of package.json
```
  "@astrojs/cloudflare": "^10.0.2",
    "@astrojs/db": "^0.10.0",
    "@astrojs/mdx": "^2.2.3",
    "@astrojs/tailwind": "^5.1.0",
    "astro": "^4.5.15"
```

astro.config.mjs:
```
export default defineConfig({
  output: "server",
  adapter: cloudflare({
    platformProxy: {
      enabled: false
    },
    functionPerRoute: false,
    routes: {
      exclude: ['/post/*']
    }
  }),
  integrations: [mdx(), db(), tailwind()],
  vite: {
    ssr: {
      external: ["url"]
    }
  }
});
```

**Comment by aklevecz** [comment]
@serdar is this happening when you deploy to Cloudflare or developing locally?

I got this error when I first deployed my app to Cloudflare, but it worked once I created a token in Astro Studio and set the `ASTRO_STUDIO_APP_TOKEN` Environment Variable in the Settings for my Pages site.

https://docs.astro.build/en/recipes/studio/#create-a-studio-app-token

**Comment by serdar** [comment]
@aklevecz no issues locally, only whilst running the deploy command (`astro build --remote && wrangler pages deploy ./dist --branch=production`).

I have the app token generated to Astro Studio and have the value set in the Environments tab in Cloudflare.

**Comment by aklevecz** [comment]
@serdar oh I see, so you're building the project locally and then pushing it? I personally like connecting my Pages to Github and allowing my pushed commits automatically go through the build steps.

But I am able to run `astro build --remote` on my machine after running:
```
# Log in to Astro Studio with your GitHub account
npx astro login

# Link to a new project by following the prompts
npx astro link
```

Does that work for you? Apologies if you had already tried that.

**Comment by alexanderniebuhr** [comment]
@matthewp Ohh.. that is new to me.. It was compatible with Cloudflare before. Did we change anything which introduced the use of `url`?

**Comment by alexanderniebuhr** [comment]
@serdar IIRC you need to have the token during build and runtime. So you would need to set it as an environmental variable on the machine/CI you use to build and as a environmental variable in the Cloudflare Dashboard for all your environments.

**Comment by serdar** [comment]
@alexanderniebuhr I have it already set in my `.env` and `.dev.vars` file

**Comment by alexanderniebuhr** [comment]
Just to make sure, you did set them in the Cloudflare dashboard? 
I don't think env or dev.var file get's pushed to Cloudflare

**Comment by serdar** [comment]
Yep, 100%. BTW calls to Astro DB don't have the same issue when called from `.astro` files - only when I'm using the Server Endpoints.

**Comment by alexanderniebuhr** [comment]
> only when I'm using the Server Endpoints

@matthewp very important detail, I think I saw a similar on Discord

**Comment by serdar** [comment]
> > only when I'm using the Server Endpoints
> 
> @matthewp very important detail, I think I saw a similar on Discord

That could be me btw :) I'm raven!

**Comment by ElianCodes** [comment]
I'm also running into this issue with the Vercel Adapter, so I don't think it's cloudflare specific. It was introduced in `astro:db` v0.10.0

**Comment by matthewp** [comment]
@ElianCodes can you file a separate issue (or ping me on discord to debug)? Would like to keep this one cloudflare specific as it's likely coming from different causes.

**Comment by matthewp** [comment]
@alexanderniebuhr Started depending on `pathToFileURL` here: https://github.com/withastro/astro/commit/157392ee44db08de0d3c01222644dae0a904044d. Can maybe do it without. But does `process.cwd()` work in Cloudflare? Probably this codepath can't work in cloudflare anyways.

**Comment by alexanderniebuhr** [comment]
I would separate both issues, since they are not the same. One is about Cloudflare support the other is that it seems there is a difference between Astro files and API Endpoints :)

**Comment by matthewp** [comment]
Talking over on discord it seems like removing the usage of `pathToFileURL` should resolve this issue.

**Comment by matthewp** [comment]
Should be fixed with `@astrojs/db@0.10.1` which should be out in a few minutes.

**Comment by serdar** [comment]
Appreciate all the effort going into this issue but still broken for me after updating to the latest version.

Issuing `astro build --remote` results in

```
Cannot create a remote client: missing app token.
  Stack trace:
    at createRemoteDatabaseClient (file:///home....
```

Astro versions:
```
    "@astrojs/check": "^0.5.10",
    "@astrojs/cloudflare": "^10.0.2",
    "@astrojs/db": "^0.10.1",
    "@astrojs/mdx": "^2.2.4",
    "@astrojs/tailwind": "^5.1.0",
    "astro": "^4.5.16",
```

ASTRO_STUDIO_APP_TOKEN set locally in `.env` and in Cloudflare

**Comment by casungo** [comment]
for me the issue is fixed, the site builds fine without the vite external url config workaround, this is my astro info output:

```
Astro                    v4.5.16
Node                     v20.7.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
                         @astrojs/svelte
                         astro:db
                         @astrojs/db/file-url
```

**Comment by serdar** [comment]
Interesting, switching to hybrid works but I need to be using `output: server` for the API endpoints to remain dynamic and not statically generated.

**Comment by aklevecz** [comment]
Everything works for me as well without using the vite external, and I use `output: server`

```
Astro                    v4.5.15
Node                     v21.5.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             astro:db
                         @astrojs/db/file-url
```

**Comment by serdar** [comment]
I'm not having much success but others have this working, so I'll put up a demo repo to try and reproduce and see if that would shed any light and what's happening.

**Comment by bkyerv** [comment]
> @serdar have you tried adding it into your build command?
> 
> `"build": "astro check && ASTRO_STUDIO_APP_TOKEN=token astro build --remote"`
> 
> Not the sexiest solution, but I can't think of a more direct way to set an environment variable

is it possible to access env vars from script? otherwise token gets exposed when commited to remote repo like github?

**Comment by chadananda** [comment]
I'm on a Macbook (M3) and have been unable to build since adding Astro DB. 

I've updated to 0.10.1 but still have the issue. I thought it was related to limited ulimit on macs but pushing to Vercel results in the same build failure. It looks like::

`ENOENT: no such file or directory, open '/vercel/path0/.vercel/output/_functions/_astro/...DqH3CDp7_2vCbLk.webp'`

I have no data in the database other than a few seeded records for testing. They work great in local dev mode with no errors.

**Comment by alexanderniebuhr** [comment]
@chadananda thanks for the update. I think the issue you face is different than the original one. The original one is related to the Cloudflare adapter, while the issue you explain look like being related to vercel. I always suggest to open a support thread on [Discord](https://astro.build/chat) first or open a new Issue on GitHub with all the informations for your project and include a minimal reproduction.

**Comment by aklevecz** [comment]
@chadananda looks like Vercel can't find a webp file. Is there an image file you aren't committing to GitHub?

**Comment by diogoribeirodev** [comment]
i still get the error when using cloudflare

**Comment by alexanderniebuhr** [comment]
@diogoribeirodev thank you for reporting that, can you please open a new issue with a minimal reproducible example which shows your setup and the error?

**Comment by YannisSefsaf** [comment]
> @serdar have you tried adding it into your build command?
> 
> `"build": "astro check && ASTRO_STUDIO_APP_TOKEN=token astro build --remote"`
> 
> Not the sexiest solution, but I can't think of a more direct way to set an environment variable

Tried this but it doesn't work for me either.

I'm using the cloudflare adapter with server mode, and I have the ASTRO_STUDIO_APP_TOKEN set in the Cloudflare dashboard as well as in my .env file.

**Comment by alexanderniebuhr** [comment]
@YannisSefsaf Please open a new issue and provide a minimal reproduction, or explanation what steps you did after using `create-astro`. I just did another project from scratch and can't reproduce any issue on Cloudflare

**Comment by chiubaca** [comment]
> for me the issue is fixed, the site builds fine without the vite external url config workaround, this is my astro info output:
> 
> ```
> Astro                    v4.5.16
> Node                     v20.7.0
> System                   Windows (x64)
> Package Manager          pnpm
> Output                   hybrid
> Adapter                  @astrojs/cloudflare
> Integrations             @astrojs/sitemap
>                          @astrojs/svelte
>                          astro:db
>                          @astrojs/db/file-url
> ```

setting my output to `hybrid` was also what fixed this for me. no need for for this  - `"build": "astro check && ASTRO_STUDIO_APP_TOKEN=token astro build --remote"` 

I had to add `export const prerender = false;` to bunch of my API routes and  asto files which was a bit annoying, but luckily I dont have a big site
