### ISSUE TITLE
transport was disconnected, cannot call "fetchModule"

### ISSUE THREAD

**Issue by mandar1jn** [withastro/astro#12611]
### Astro Info

```block
Astro                    v5.0.1
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Modifying tsconfig.json while the dev server is running throws a "transport was disconnected, cannot call "fetchModule"" exception

Steps:
1. create a project from the blog temple
2. start the dev server
3. open one of the blog posts
4. modify the tsconfig.json
5. look at the console

### What's the expected result?

No exception should be thrown

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog?file=tsconfig.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't seem to reproduce this, but it looks like a race condition happening. Can you share a stacktrace of the error?

**Comment by mandar1jn** [comment]
This is the stacktrace when running with --verbose:
```
2024-12-05T10:25:44.724Z astro:vite Error when evaluating SSR module /home/projects/owainyqygb.github/src/content.config.ts:
|- Error: transport was disconnected, cannot call "fetchModule"
    at reviveInvokeError (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:562:17)
    at Object.invoke (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:649:15)
    at async SSRCompatModuleRunner.getModuleInformation (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1221:73)
    at async request (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1243:88)
    at async eval (/home/projects/owainyqygb.github/src/content.config.ts:3:44)
    at async ESModulesEvaluator.runInlinedModule (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1074:5)
    at async SSRCompatModuleRunner.directRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1300:61)
    at async SSRCompatModuleRunner.directRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:30673:23)
    at async SSRCompatModuleRunner.cachedRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1195:76)
    at async SSRCompatModuleRunner.import (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1132:12)

2024-12-05T10:25:44.728Z astro:vite Error when evaluating SSR module file:///home/projects/owainyqygb.github/node_modules/@astrojs/mdx/dist/server.js:
|- Error: transport was disconnected, cannot call "fetchModule"
    at reviveInvokeError (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:562:17)
    at Object.invoke (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:649:15)
    at async SSRCompatModuleRunner.getModuleInformation (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1221:73)
    at async request (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1243:88)
    at async eval (/home/projects/owainyqygb.github/node_modules/astro/dist/core/errors/printer.js:3:44)
    at async ESModulesEvaluator.runInlinedModule (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1074:5)
    at async SSRCompatModuleRunner.directRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1300:61)
    at async SSRCompatModuleRunner.directRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:30673:23)
    at async SSRCompatModuleRunner.cachedRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1195:76)
    at async eval (/home/projects/owainyqygb.github/node_modules/astro/dist/core/errors/errors.js:3:44)

11:25:44 [ERROR] transport was disconnected, cannot call "fetchModule"
  Location:
    /home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:562:17
  Stack trace:
    at reviveInvokeError (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:562:17)
    at async SSRCompatModuleRunner.getModuleInformation (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1221:73)
    at async eval (/home/projects/owainyqygb.github/node_modules/astro/dist/core/errors/printer.js:3:44)
    at async SSRCompatModuleRunner.directRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1300:61)
    at async SSRCompatModuleRunner.cachedRequest (file:///home/projects/owainyqygb.github/node_modules/vite/dist/node/module-runner.js:1195:76)
    ```

**Comment by vnphanquang** [comment]
Might not be helpful at all, but I got the same issue today when introducing a custom Vite plugin to a SvelteKit project (no Astro specifics). Problem seems to be plugin A is generating some modules that were being imported by plugin B. I also noticed that HMR is broken when this error is observed. In my case shifting plugin order, using different hook, and playing around with `enforce` solved the problem.

**Comment by aalfiann** [comment]
I got this same issue. 


Sometimes this happened and sometimes its solved by itself (i didn't change the code). 

Yeah, this is hard to reproduce.

**Comment by delucis** [comment]
Confirmed again today that the error still reproduces in Astro 5.13.2.

**Comment by florian-lefebvre** [comment]
Probably in a different context but I got the same error when doing `server.ssrLoadModule` while syncing 🤔

**Comment by Arecsu** [comment]
I experience this from time to time as well. It happens far more in Windows WSL than my macOS and Linux systems.

```
# ✔ Generate outputs
#   ℹ Watching for changes in /home/arecsu/martyr/martyrio...
# pnpm dev:codegen exited with code 0
--> Sending SIGTERM to other processes..
#  ELIFECYCLE  Command failed.
# 23:09:04 [ERROR] transport was disconnected, cannot call "fetchModule"
#   Stack trace:
#     at /home/arecsu/martyr/martyrio/node_modules/.pnpm/vite@6.4.1_@types+node@24.10.0_jiti@2.6.1_sass@1.93.3_tsx@4.20.6_yaml@2.8.1/node_modules/vite/dist/node/module-runner.js:548:17
#     [...] See full stack trace in the browser, or rerun with --verbose.
# pnpm dev:astro exited with code SIGTERM
 ELIFECYCLE  Command failed with exit code 1.                         
```

It seems that it usually happens in the first time that I open the dev server at boot, and/or when I'm requesting `localhost:4321` just after entering `pnpm run dev` but without booting up completely. I also have the feeling that Firefox seems to trigger this particular error more than Chrome browsers? Hard to reproduce

**Comment by igor-ye** [comment]
I encountered the same problem running build on WSL2.
Resolved by cleaning up all astro-generated files. So add 

`"clean": "rm -rf ./.astro/ && rm -rf ./node_modules/.astro/ && rm -rf ./dist/",`

to scripts in package.json (dist folder cleaning just for consistency with script name). And just execute `npm run clean` when you face this error again.

**Comment by delucis** [comment]
This bug is still reproducible with Astro v6. The dev server logs errors when `tsconfig.json` is modified in any way (even just adding some meaningless whitespace).

The error does not display in the browser error overlay (I don’t remember if it did with Astro v5) and things appear to keep working but the error is still logged to the terminal.

**Comment by ematipico** [comment]
Probably related to https://github.com/vitejs/vite/issues/22011

**Comment by delucis** [comment]
The upstream issue has been closed and we just updated to Vite 8 in Astro 7 so fingers crossed hopefully this is fixed too. I’ll close this and if anyone hits this again please create a new issue!
