### ISSUE TITLE
Content layer schema references randomly break

### ISSUE THREAD

**Issue by cabaucom376** [withastro/astro#12680]
### Astro Info

```block
Astro                    v5.0.3
Node                     v23.3.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js
```

### Describe the Bug

When editing content files and changing the names of referenced id's a lot occasionally astro will lock up and not allow the site to be built with an error like this:
```
[InvalidContentEntryDataError] features → core/shards data does not match collection schema.
category: Reference to categories invalid. Entry core does not exist.
```
The category `core` has been verified to exist and is defined properly in a yaml file.

./content/categories.yaml:
```yaml
core:
  sequence: 0
  title: Core
editor:
  sequence: 1
  title: Editor
qol:
  sequence: 3
  title: Quality of Life
connectivity:
  sequence: 4
  title: Connectivity
extensibility:
  sequence: 5
  title: Extensibility
intelligence:
  sequence: 6
  title: Intelligence
platforms:
  sequence: 7
  title: Platforms
```
./src/content.config.ts:
```typescript
import { z, defineCollection, reference } from "astro:content";
import { file, glob } from "astro/loaders";

const categories = defineCollection({
  loader: file("content/categories.yaml"),
  schema: z.object({
    sequence: z.number(),
    title: z.string(),
  }),
});

const features = defineCollection({
  loader: glob({ pattern: "**/*.{md, mdx}", base: "content/features" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
    sequence: z.number(),
    category: reference("categories"),
    status: z.enum([
      "concept",
      "confirmed",
      "upcoming",
      "development",
      "beta",
      "complete",
    ]),
  }),
});

export const collections = {
  categories: categories,
  features: features,
};
```
./content/features/core/shards.md:
```markdown
---
title: "Shards"
description: "..."
sequence: 0
category: core
status: "development"
---
```

This is really hard to reproduce, but it has happened to me twice now in the last 3 days after my V5 migration, once initially while setting up the glob and file loaders, and another while simply modifying the names of categories. When these instances occur, not even reverting the project back to a time it was functional via git allows for it to build. The only solution I have found after many hours of nothing was this:
1. Comment out the problem schema field, ex: `category: reference("categories"),`
2. Run astro dev, and it should build fine
3. Quit the run
4. Uncomment out the same field
5. Run astro dev again

I feel this is a bug because nothing is changing at all about the schema, yet it can go from not building at all to building perfectly fine.

### What's the expected result?

The website should build and not get locked up randomly on reference data updates.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-chwz8xrn?file=src%2Fcontent.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FraserThompson** [comment]
I started experiencing this too after upgrading to Astro 5. It feels like some sort of race condition, where one collections entries aren't being processed before the other collection references them or something? If I change the reference to an old one, run astro dev, then kill it and change it back to the new one, it works.

**Comment by cestef** [comment]
Not quite the same bug, but likely related as it also looks like a race condition somewhere:
```
13:07:32 [glob-loader] Reloaded data from shamir/index.md
Local icons changed, reloading
Local icons changed, reloading
Local icons changed, reloading
The collection "blog" does not exist or is empty. Ensure a collection directory with this name exists.
13:07:38 [WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/posts/shamir`.

Possible dynamic routes being matched: src/pages/posts/[...slug].astro.
13:07:38 [404] /posts/shamir 2ms
Local icons changed, reloading
13:07:38 [200] /posts/shamir 307ms
```

When editing a `.md` file defined in the `blog` content layer collection:

```ts
// ...

export const BlogSchema = z.object({
	title: z.string(),
	tags: z.array(z.string()),
	image: z.string().optional(),
	description: z.string(),
	date: z.date().transform((val) => new Date(val)),
	growth: GrowthSchema.default("seed"),
	related: z.array(reference("blog")).optional(),
});

const blogCollection = defineCollection({
	loader: glob({ pattern: "**/[^_]*.md", base: "./src/data/blog" }),
	schema: BlogSchema,
});

export const collections = {
	blog: blogCollection,
};
```

The glob loader effectively detects the change and fires a reload on the browser, but the development server seems not be be ready instantly, and I need to refresh it manually a second time to get the actual content. 

The reloaded content also sometimes doesn't match the updated one (the old version is still being considered as "current" in the cache or something like that)

After removing the `related: ... reference(...)` line from my zod schema, it looks like this isn't happening anymore, even though the re-rendering time feels way longer than on astro v4.

**Comment by ascorbic** [comment]
Could any of the people reporting this confirm whether this is present in the latest version of Astro? We've made a few changes to prevent content collection race conditions so a lot of these sort of issues are now working.

**Comment by aluciu** [comment]
hi, i just verified on astro v5.1.5 and i get the same errors:
```
[InvalidContentEntryDataError] articles → article-name data does not match collection schema.
artists.0: Reference to artists could not be resolved: store not available.
This is an Astro bug, so please file an issue at https://github.com/withastro/astro/issues.
```

**Comment by BuckyBuck135** [comment]
2 of my projects are running into the same issue. Any time I update something connected to a reference, it breaks the dev server.
Reloading the window, rebooting dev server or rebooting computer won't help.
Removing the reference in the collection schema gets rid of the error (but obviously impedes other features)

Astro v5.1.7

```ts
const blogCollection = defineCollection({
	loader: glob({ pattern: "**/[^_]*{md,mdx}", base: "./src/data/blog" }),
	schema: ({ image }) =>
		z.object({
			title: z.string(),
			description: z.string(),
			// commenting out the authors reference for now
			// authors: z.array(reference("authors")),
			heroImage: image(),
		}),
});

// authors
const authorsCollection = defineCollection({
	loader: glob({ pattern: "**/[^_]*{md,mdx}", base: "./src/data/authors" }),
	schema: ({ image }) =>
		z.object({
			name: z.string(),
			avatar: image(),
		}),
});

```

**Comment by ascorbic** [comment]
@grctest that's different. The issue there is that the schema is for a single item, not the array. Change the schema to:

```ts
const poolSchema = z.object({
        id: z.string(),
        asset_a_id: z.string(),
        asset_a_symbol: z.string(),
        asset_b_id: z.string(),
        asset_b_symbol: z.string(),
        share_asset_symbol: z.string(),
        share_asset_id: z.string(),
        balance_a: z.union([z.string(), z.number()]), // Adjusted to accept both string and number
        balance_b: z.union([z.string(), z.number()]), // Adjusted to accept both string and number
        taker_fee_percent: z.number()
    })
```

You shouldn't need to define a custom loader either. The one you've shown is effectively the same as the default loader

**Comment by grctest** [comment]
Thanks, I got past the errors with your suggestion.. but then ran into the error `"astro:content" module is only available server-side` since v5 this was the wrong route to go down.. dang lol..

**Comment by Fermain** [comment]
I'm getting this on latest (5.3.1):

```ts
const site_settings = defineCollection({
  loader: file("./src/config/_default/site.config.json"),
  schema: z.object({
    name: z.string(),
    title: z.string(),
    description: z.string().optional(),
    entities: z.array(
      z.object({
        title: z.string(),
        country: z.string(),
        registration: z.string().optional(),
      })
    ),
  }),
});
```

```sh
[InvalidContentEntryDataError] site_settings → name data does not match collection schema.
Expected type `"object"`, received `"string"`
```

```json
{
  "name": "test",
  "title": "test",
  "description": "test",
  "entities": [
    {
      "title": "test",
      "country": "test",
      "registration": "test"
    }
  ],
  "logo": "@assets/images/logo.svg"
}
```

**Comment by ascorbic** [comment]
This issue was for schemas that use the `reference` feature, not for arbitrary schema errors. That issue was fixed. If your issue isn't about `reference()` then this is not relevant.

**Comment by aluciu** [comment]
I can confirm that the issue persists. 
If I execute `npm run dev` from the terminal, occasionally, I encounter the following error:
```
[InvalidContentEntryDataError] articles → article-title data does not match collection schema.
artists.0: Reference to artists could not be resolved: store not available.
This is an Astro bug, so please file an issue at https://github.com/withastro/astro/issues.
```
Therefore, I discovered a potential solution to enable local server development. Initially, I remove the `.astro` folder, and then I execute `npm run dev` again.

However, if I launch the development server from Visual Studio Code, I do not encounter this error.

I am using Astro version 5.3.1
