### ISSUE TITLE
Browser shows "Cannot read properties of null (reading 'invalidateTypeCache')" error with "@astrojs/vue" integration

### ISSUE THREAD

**Issue by Smart-Ace-Designs** [withastro/astro#12969]
### Astro Info

```block
Astro                    v5.1.5
Node                     v22.12.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/vue
```

### Describe the Bug

1. Deploy new Astro project with "npm create astro@latest" (blank project; select option to install dependencies)
2. Run "npx astro add vue"
3. Run "npm run dev"
4. Open browser to localhost:4321 - appears normal and default page is displayed
5. Close browser and kill dev environment
6. Run "npm run dev" again
7. Again, open browser - this time "Cannot read properties of null (reading 'invalidateTypeCache')" is displayed
8. Refresh browser and default page is displayed and error goes away
9. Repeat steps 5-8 with same results every time

![image](https://github.com/user-attachments/assets/47b1fdae-d7cb-4fd5-b7cd-9b79eff3f07b)

Tried same process on another machine, same results...does not appear to be isolated to a single machine.

For the StackBlitz reproduction, I am just including the default template provided for Vue:
https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-vue?file=README.md&on=stackblitz

Ctrl-c to stop the initial dev environment and then run "npm run dev" again, and you will see the error show up immediately:

![image](https://github.com/user-attachments/assets/69de725a-c66c-4d0d-98cf-c31bdf3a2bf4)

### What's the expected result?

Default page should load each time with no error, when Astro Vue integration is added to project.

![image](https://github.com/user-attachments/assets/9ea372fc-17fa-4c77-9e4c-628e6cfa72f2)

...should not have to refresh browser (F5) to get this to appear.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-vue?file=README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Smart-Ace-Designs** [comment]
Appears to be fixed now with the astro 5.1.7 and/or @astrojs/vue 5.0.5 releases on 1-15-2025.

Thank you for fixing.

**Comment by florian-lefebvre** [comment]
Still facing in this in a project

**Comment by Smart-Ace-Designs** [comment]
Yeah...sorry for prematurely closing it...thought it was fixed.  But noticed it come back too, last night.  Seems to be very sporadic as you mentioned...sometimes is just works.

**Comment by spaceemotion** [comment]
Can confirm that we get the same issue still as well, but after a page refresh the error goes away. It seems to always come in when the page loads right after you started the server.

**Comment by Smart-Ace-Designs** [comment]
Workaround seems to work...assuming you meant "astro.config.mjs":

```js
// @ts-check
import { defineConfig } from "astro/config";

import vue from "@astrojs/vue";
import * as compiler from "vue/compiler-sfc";

// https://astro.build/config
export default defineConfig({
  integrations: [vue({ compiler })],
});
```

For anyone else having the problem...

**Comment by Smart-Ace-Designs** [comment]
Excellent.  Thank you 😃

**Comment by MellKam** [comment]
I'm still running into this problem with `astro@5.3.0` and `@astrojs/vue@5.0.6`

**Comment by florian-lefebvre** [comment]
Can you provide a minimal reproduction?

**Comment by florian-lefebvre** [comment]
You're right! Should be released early next week
