### ISSUE TITLE
Local fonts are not loading properly using Experimental fonts API

### ISSUE THREAD

**Issue by coderdiaz** [withastro/astro#14438]
### Astro Info

```block
Astro                    v5.14.0
Node                     v22.16.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/react
                         @astrojs/sitemap
                         @astrojs/mdx
```

### Describe the Bug

I have updated Astro from 5.13.9 to 5.14.0 and now the fonts are not loading correctly.

<img width="955" height="361" alt="Image" src="https://github.com/user-attachments/assets/f03265d7-335b-4632-8ab9-b06931359538" />

Maybe will be related to a missing `-` between generated font name.

### What's the expected result?

The fonts need load correctly without 404 error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kfzzjata?file=src%2Flayouts%2FBaseLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by saadrana** [comment]
Hi, this fix was released in v5.14.1 right? I still seem to be having this issue on the latest version. Is there anything else you need to change after updating to get it working in dev again. I also tried updating the astro version in the stackblitz attached to this issue and got the same result.

**Comment by andrewdisley** [comment]
> Hi, this fix was released in v5.14.1 right? I still seem to be having this issue on the latest version. Is there anything else you need to change after updating to get it working in dev again. I also tried updating the astro version in the stackblitz attached to this issue and got the same result.

Second that, we are also experiencing this still broken in 5.14.1:

<img width="1748" height="1008" alt="Image" src="https://github.com/user-attachments/assets/cde53a23-6741-4393-b53b-4dcb42bf9489" />

and for config context, it’s a local font.

<img width="1758" height="756" alt="Image" src="https://github.com/user-attachments/assets/9a5f01eb-c4cb-4340-bde2-b22d09259bd5" />

@florian-lefebvre do we need to open a new issue?

**Comment by florian-lefebvre** [comment]
I'm looking into it!

**Comment by florian-lefebvre** [comment]
We should release a patch on Monday
