### ISSUE TITLE
🐛 BUG: Aliases not being detected with `Astro.resolve`

### ISSUE THREAD

**Issue by naiyerasif** [withastro/astro#1957]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

yarn

### What operating system are you using?

Windows 11

### Describe the Bug

I configured an alias in `jsconfig.json` as follows.

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"],
      "@/styles/*": ["src/styles/*"],
    }
  }
}
```

I used the aliases to import styles in `BaseHead.astro`

```astro
<meta charset="utf-8" />
<link rel="icon" type="image/x-icon" href="/favicon.ico" />
<meta name="viewport" content="width=device-width" />
<title>Welcome to Astro</title>
<link rel="stylesheet" type="text/css" href={Astro.resolve('@/styles/main.scss')} />
```

And imported the component in `index.astro`

```astro
---
import BaseHead from '@/components/BaseHead.astro'
---

<html lang="en">

<head>
	<BaseHead />
</head>

<body>
	<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
</body>

</html>
```

## Expected Result

The minimal app should have loaded at http://localhost:3000

## Actual Result

Got 500 at `/` with the following error.

```
Failed to resolve import "@/components/BaseHead.astro" from "src\pages\index.astro". Does the file exist?

Error: Failed to resolve import "@/components/BaseHead.astro" from "src\pages\index.astro". Does the file exist?
    at formatError (E:\web\astro-alias-issue\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:42211:46)
    at TransformContext.error (E:\web\astro-alias-issue\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:42207:19)
    at normalizeUrl (E:\web\astro-alias-issue\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:67272:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransformContext.transform (E:\web\astro-alias-issue\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:67412:57)
    at async Object.transform (E:\web\astro-alias-issue\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:42418:30)
    at async doTransform (E:\web\astro-alias-issue\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:56765:29)
```

## Additional Info

- Reproduce without sass : https://github.com/naiyerasif/astro-alias-issue/commit/5a2c22cc3949bbd4538f24f396a486f3fac46356
- Reproduce with sass: https://github.com/naiyerasif/astro-alias-issue/commit/b4c1bcbde6c8601d93c2471738834b4ba4d110e5
- When I use relative paths, everything works as expected.

### Link to Minimal Reproducible Example

https://github.com/naiyerasif/astro-alias-issue

**Comment by natemoo-re** [comment]
Does `<link rel="stylesheet" type="text/css" href="@/styles/main.scss" />` work? I don't think you need `Astro.resolve` in this case. In fact, it might be causing the problem.

**Comment by naiyerasif** [comment]
The issue is not specific to `Astro.resolve`. None of the configured aliases are working, irrespective of whether I use them in `import`s or `Astro.resolve`.

I checked with `<link rel="stylesheet" type="text/css" href="@/styles/main.scss" />` and got the same result. The alias is not getting replaced with the actual path.

**Comment by natemoo-re** [comment]
Hmm, maybe @jonathantneal can take a look at this one?

**Comment by jonathantneal** [comment]
I can confirm this issue. Reproduction @ https://stackblitz.com/edit/github-jz4glh?file=tsconfig.json&on=stackblitz using `tsconfig.json`.

The `jsconfig.json` (or `tsconfig.json`) is working within the Astro file, which is why `@/components/BaseHead.astro` is successfully imported. However, `<link rel="stylesheet" type="text/css" href={Astro.resolve('@/styles/main.scss')} />` is not pointing to the right file.

I suspect that internally they are not using the same file resolution.

I’ll take a look at how we get `Astro.resolve` to use the same resolver.

**Comment by naiyerasif** [comment]
> This is why @/components/BaseHead.astro is imported, but the href in the following is not:
>
> ```html
> <link rel="stylesheet" type="text/css" href={Astro.resolve('@/styles/main.scss')} />
> ```

@jonathantneal Even the `import`s in the frontmatter of `.astro` files is not working for me.

**Comment by Mikkel-T** [comment]
Hey @naiyerasif can you please check if this is still the case with version `0.21.10`? Aliases on windows should have been fixed in that version.

**Comment by naiyerasif** [comment]
@Mikkel-T v0.21.10 has fixed imports of `.astro` components. However, SCSS aliases are still not working. See screenshot below on what's happening with SCSS imports.

![image](https://user-images.githubusercontent.com/19614213/144803900-dfbcc5bd-8a66-4435-9387-4012f50b21bd.png)

**Comment by jonathantneal** [comment]
We‘ve decided to deprecate `Astro.resolve`, and provide a better mechanism for this. `Astro.resolve` was only a relative path resolver. Please [read it over](https://github.com/withastro/rfcs/blob/main/active-rfcs/0000-relative-url-scheme.md) and let us know how you feel about this direction.

Top level imports would still have the ability to resolve from modules.
