### ISSUE TITLE
🐛 BUG: Node imports still broken in 0.21.3

### ISSUE THREAD

**Issue by innermatrix** [withastro/astro#2017]
### What version of `astro` are you using?

0.21.3

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Can't build an Astro project that depends on an npm package that depends on node. See MWE. Error is:

```
12:07:18 AM [vite] Error when evaluating SSR module /node_modules/merge2/index.js?v=788f0240:
ReferenceError: require is not defined
    at /node_modules/merge2/index.js?v=788f0240:9:16
    at instantiateModule (/home/projects/github-t3hheb-q5u9qb/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:66510:15)
```

Unclear if related to #1852 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t3hheb-q5u9qb

**Comment by natemoo-re** [comment]
Hey, thanks for opening an issue! Sorry this is still causing trouble.

The gist of this issue is that Vite has some logic to transform dependencies during SSR. In this case, `merge2` appears to be a [CJS](https://github.com/teambition/merge2/blob/master/index.js) package but is being loaded in an ESM context. 

I tagged this issue as `upstream` because Vite is working on a ton of SSR fixes that Astro will benefit from soon. Hopefully those updates will resolve this, since I wasn't able to configure [SSR externals](https://vitejs.dev/guide/ssr.html#ssr-externals) to handle this package properly. 😞

**Comment by innermatrix** [comment]
Ahh, and vite is new to 0.21. Makes sense — thanks!

**Comment by lloydjatkinson** [comment]
Is this why I'm getting the following?

```
Cannot read properties of undefined (reading '0')
    at Context.load (C:\Users\Lloyd\source\repos\the-repo\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:21183:65)
    at Object.load (C:\Users\Lloyd\source\repos\the-repo\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:42399:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doTransform (C:\Users\Lloyd\source\repos\the-repo\node_modules\astro\vendor\vite\dist\node\ch
    ```

**Comment by natemoo-re** [comment]
> Is this why I'm getting the following?
> 
> ```
> Cannot read properties of undefined (reading '0')
>     at Context.load (C:\Users\Lloyd\source\repos\the-repo\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:21183:65)
>     at Object.load (C:\Users\Lloyd\source\repos\the-repo\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:42399:50)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async doTransform (C:\Users\Lloyd\source\repos\the-repo\node_modules\astro\vendor\vite\dist\node\ch
>     ```
> ```

I think this is the same as https://github.com/withastro/astro/issues/2053! Should be fixed in `astro@0.21.6`!

**Comment by jonathantneal** [comment]
Confirming the original issue listed here is still present in Astro v0.21.12.

```
require is not defined
ReferenceError: require is not defined
    at /node_modules/merge2/index.js?v=655f942f:7:16
    at instantiateModule (/home/projects/github-t3hheb-q5u9qb/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:66516:15)
```

**Comment by naiyerasif** [comment]
This issue is still present in Astro v0.22.1 and has unfortunately become a blocker ☹️

```shell
11:18:28 AM [vite] Error when evaluating SSR module /node_modules/lodash.deburr/index.js?v=0aca6742:
ReferenceError: module is not defined
    at /node_modules/lodash.deburr/index.js?v=0aca6742:257:1
    at instantiateModule (C:\Users\Default\remnant\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:66516:15)
11:18:28 AM [vite] Error when evaluating SSR module /node_modules/@sindresorhus/transliterate/index.js?v=0aca6742:
ReferenceError: module is not defined
    at /node_modules/lodash.deburr/index.js?v=0aca6742:255:1
    at instantiateModule (C:\Users\Default\remnant\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:66516:15)
11:18:28 AM [vite] Error when evaluating SSR module /node_modules/@sindresorhus/slugify/index.js?v=0aca6742:
ReferenceError: module is not defined
    at /node_modules/lodash.deburr/index.js?v=0aca6742:253:1
    at instantiateModule (C:\Users\Default\remnant\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:66516:15)
11:18:28 AM [vite] Error when evaluating SSR module /src/library/slugger.mjs:
ReferenceError: module is not defined
    at /node_modules/lodash.deburr/index.js?v=0aca6742:251:1
    at instantiateModule (C:\Users\Default\remnant\node_modules\astro\vendor\vite\dist\node\chunks\dep-35df7f96.js:66516:15)
```

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

One of the latest astro updates currently in the `@next` release moves upgrades to the latest version of Vite, and moves us to using vite's dev server rather than a custom one for Astro, the combination should have this issue taken care of :+1:
