### ISSUE TITLE
🐛 BUG: Latest Astro broke Preact component rendering

### ISSUE THREAD

**Issue by ElianCodes** [withastro/astro#2169]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Stackblitz / any

### Describe the Bug

When importing a `.tsx` Preact component in the latest 0.21.12 release, the build fails with a 500 error explaining that the component can't be found or rendered.

See the basic Astro Framework Preact example

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-preact

**Comment by FredKSchott** [comment]
Verified that this is happening on old versions of Astro as well. Tracing to see if its a new preact release causing this.

**Comment by FredKSchott** [comment]
Update: can't reproduce in our monorepo. 
Also, checked the preact changelog and can't see anything obviously broken: https://github.com/preactjs/preact/releases

**Comment by FredKSchott** [comment]
Update: tracked it down to something in preact v10.6. Not sure what yet but we can at least push a fix for this now to pin to v10.5 until we can figure that out.

**Comment by natemoo-re** [comment]
> Update: possibly related to `Support hydrating html comments (#3327, thanks @JoviDeCroock)`

Yeah... that sounds like it would have an impact!

**Comment by JoviDeCroock** [comment]
Hey all,

Just noticed this, is there a good way for me to debug this as the origin of this issue hints at the error being masked 😅 would love to help out, it would be interesting if the PR in question breaks something as the attribute in question seems to be present on all but comment-nodes.

**Comment by developit** [comment]
This appears to be somehow related to a change we made to the timing of useEffect. @natemoo-re any way you see that being connected here? I can't imagine how it relates to hydration...

**Comment by JoviDeCroock** [comment]
Hmm, do you lot run effects on the server? The error seems to be thrown from a Node process as it alludes to document being undefined.

**Comment by natemoo-re** [comment]
We aren't running effects on the server AFAIK, but Astro's Preact renderer is mostly a wrapper around `preact-render-to-string`. Any chance there's a necessary update to that package that we missed?

**Comment by natemoo-re** [comment]
This is pretty much all our Preact renderer does on the server https://github.com/withastro/astro/blob/main/packages/renderers/renderer-preact/server.js#L28

I can try to get the underlying error and see if there's more detail! Hold tight.

**Comment by JoviDeCroock** [comment]
So.. This error seems to allude to noone claiming the renderer

**Comment by natemoo-re** [comment]
Yep, that's just a bad error on our end. I narrowed down the actual issue from Preact's side. Kinda weird but it seems like `Fragment` is breaking?

```tsx
import { h, Fragment } from 'preact';
import { useState } from 'preact/hooks';
import './Counter.css';

export default function Counter({ children }) {
  const [count, setCount] = useState(0);
  const add = () => setCount((i) => i + 1);
  const subtract = () => setCount((i) => i - 1);

  return (
    <>
      <div class="counter">
        <button onClick={subtract}>-</button>
        <pre>{count}</pre>
        <button onClick={add}>+</button>
      </div>
      <div class="counter-message">{children}</div>
    </>
  );
}
```

generates the following

```html
<undefined><div class="counter"><button>-</button><pre>0</pre><button>+</button></div><div class="counter-message"><astro-fragment><h1 class="astro-ZE4EHHQA">Hello, Preact!</h1></astro-fragment></div></undefined>
```

If you reference `Fragment` directly (like `<Fragment>`), we get the correct output of

```html
<div class="counter"><button>-</button><pre>0</pre><button>+</button></div><div class="counter-message"><astro-fragment><h1 class="astro-ZE4EHHQA">Hello, Preact!</h1></astro-fragment></div>
```

**Comment by natemoo-re** [comment]
We're using `@babel/plugin-transform-react-jsx@7.16.0` and the `{ runtime: 'automatic', importSource: 'preact' }` options.

**Comment by JoviDeCroock** [comment]
Euhmmm, I have no idea how that can happen 😅 especially given the changes in that version

**Comment by JoviDeCroock** [comment]
Yes so for me it works on 10.6.2 but not on 10.6.3

**Comment by natemoo-re** [comment]
Confirming that on my end as well. 

So here's the Babel output for the `<>` code...

```js
import { useState } from "preact/hooks";
import "./Counter.css";
import { jsx as _jsx } from "preact/jsx-runtime";
import { jsxs as _jsxs } from "preact/jsx-runtime";
import { Fragment as _Fragment } from "preact/jsx-runtime";
export default function Counter({
  children
}) {
  const [count, setCount] = useState(0);

  const add = () => setCount(i => i + 1);

  const subtract = () => setCount(i => i - 1);

  return _jsxs(_Fragment, {
    children: [_jsxs("div", {
      class: "counter",
      children: [_jsx("button", {
        onClick: subtract,
        children: "-"
      }), _jsx("pre", {
        children: count
      }), _jsx("button", {
        onClick: add,
        children: "+"
      })]
    }), _jsx("div", {
      class: "counter-message",
      children: children
    })]
  });
}
```

with the broken output

```html
<undefined><div class="counter"><button>-</button><pre>0</pre><button>+</button></div><div class="counter-message"><astro-fragment><h1 class="astro-ZE4EHHQA">Hello, Preact!</h1></astro-fragment></div></undefined>
```

When using `<Fragment>` the Babel output is...

```js
import { Fragment } from "preact";
import { useState } from "preact/hooks";
import "./Counter.css";
import { jsx as _jsx } from "preact/jsx-runtime";
import { jsxs as _jsxs } from "preact/jsx-runtime";
export default function Counter({
  children
}) {
  const [count, setCount] = useState(0);

  const add = () => setCount(i => i + 1);

  const subtract = () => setCount(i => i - 1);

  return _jsxs(Fragment, {
    children: [_jsxs("div", {
      class: "counter",
      children: [_jsx("button", {
        onClick: subtract,
        children: "-"
      }), _jsx("pre", {
        children: count
      }), _jsx("button", {
        onClick: add,
        children: "+"
      })]
    }), _jsx("div", {
      class: "counter-message",
      children: children
    })]
  });
}
```

and the HTML output does not have the wrapping `<undefined>`.

**Comment by JoviDeCroock** [comment]
Weird that it evaluates to `undefined` given that this is correctly exported according to this https://www.runpkg.com/?preact@10.6.3/jsx-runtime/dist/jsxRuntime.mjs

**Comment by natemoo-re** [comment]
I was just trying to check that, seeing it locally in my `node_modules` as well. We're loading this code through Vite so it's entirely possible this issue is on their end.

**Comment by JoviDeCroock** [comment]
It's weird that it happens between versions though, I'm wondering if I published with a newer version of microbundle by accident 😅

**Comment by matthewp** [comment]
Can we pin to `10.6.2` temporarily then?

**Comment by matthewp** [comment]
@JoviDeCroock my guess is that babel just checks for `Fragment` JSX usage and doesn't resolve the alias in the import. That's what appears different from @natemoo-re's snippet.

**Comment by JoviDeCroock** [comment]
I just tried building Preact from source and it seems to work correctly when using this build with astro

**Comment by natemoo-re** [comment]
> I just tried building Preact from source and it seems to work correctly when using this build with astro, so this issue must be an interaction with the bundler/transpiler

Awesome, thanks for taking some time to debug this @JoviDeCroock! In that case it seems like a potential issue on our end. We'll keep trying to figure this out!

**Comment by JoviDeCroock** [comment]
I'm testing whether a new build fixes this issue (in case I used a newer microbundle) then we solve this for you lot for the time being. This means that 10.6.3 won't work for astro but 10.6.4 will, hope this can help you lot out.

When this finishes https://ci.codesandbox.io/status/preactjs/preact/pr/3371/builds/197450 I'll check it with the reproduction, if it does it means I probably used a newer microbundle version to build 10.6.3 which in theory shouldn't break stuff but 🤷‍♂️

**Comment by JoviDeCroock** [comment]
![image (1)](https://user-images.githubusercontent.com/17125876/145464232-55d3e2fb-9e5f-49bd-9cb7-aa41db2b9880.png)

Okay so I narrowed down the issue, the left version works and the right does not. On the left we first import `Fragment` and then export while on the right we directly export.

**Comment by natemoo-re** [comment]
Interesting! I'm really curious if that's a pattern our version of Vite is unable to pick up on or something...

Regardless, thank you for digging into this. Really appreciate it! We'll bump to `preact@10.6.4` when it's out!

**Comment by marvinhagemeister** [comment]
We found the root cause for this. It's the way node shims commonjs modules, when they are loaded via a dynamic import. It will only forward named imports if they're not defined via a getter. 

```js
// CommonJS module

// works
exports.foo = "foo";

// Doesn't work
Object.defineProperty(exports, 'bar', {
  enumerable: true,
  get: function () {
    return 'bar';
  },
});
```

The right question to ask is how that getter came to be. It's usually introduced by bundlers to introduce interop with ESM. In ESM a module entry cannot be dynamically changed, but one can in CommonJS! So the getter is meant to freeze the module object. An alternative to that is `Object.freeze()`. This is usually done without notice by bundlers. In our case we have different versions in our tooling in some branches in the Preact repo and the `10.6.3` version was published with the wrong build tools version.

The fixed version looks like this:

```js
// CommonJS module
exports.foo = "foo";
exports.bar = "bar"
```

@JoviDeCroock just published `10.6.4` which includes the fix and we recommend updating to that 🎉
