### ISSUE TITLE
🐛 BUG: Svelte `Date.getSeconds` causes TypeError: Cannot read properties of undefined (reading 'querySelector')

### ISSUE THREAD

**Issue by JosNun** [withastro/astro#2189]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Windows (WSL) & Stackblitz

### Describe the Bug

When calling `Date.getSeconds()` in a Svelte component, the following error is thrown after the second refresh:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at onVisible (visible.ts:10)
    at index.astro?html-proxy&index=0.js:2
```

- It appears to only happen when running in dev mode.
- The error is thrown when calling `getSeconds()` after a `new Date()`, and when calling `getSeconds()` on an existing date variable.
- `Date.getMinutes()` doesn't seem to cause the issue.
- Doesn't throw when rendering the component with `client:only`
- The error isn't thrown on the first load, only subsequent refreshes (not 100% sure about this one)
- [Question / discussion in the Discord support channel](https://discord.com/channels/830184174198718474/845451724738265138/916905523608191051) 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-adneju?file=src/components/Example.svelte

**Comment by jonathantneal** [comment]
This appears to have been fixed, using the same reproduction link.

**Comment by jonathantneal** [comment]
Please reach out if you experience it again, either at another page, or at the same page (and I’m just having unexpected success).

**Comment by JosNun** [comment]
Seems to be still occurring in the reproduction example. I'll note that you have to refresh to get it to error, and the initial render still works fine, but any subsequent client-side renders wouldn't work 
![image](https://user-images.githubusercontent.com/7729878/150176974-73683277-70fe-4e8c-a2a9-3d259563df27.png)

**Comment by boehs** [comment]
Can confirm based on @JosNun's comment,

@jonathantneal this can be reopened, astro `22.14`

**Comment by jadonn** [comment]
I also get this error with Svelte. I got it on 0.22.9, then I updated to 0.22.17 today, but it did not change anything. I am using Svelte on WSL and npm.

I am just trying to add a simple function using JavaScript that compares some strings to one another. This is the error I am seeing:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at onVisible (visible.ts:10).
```
I get the same error if I use `client:load`, `client:visible`, or `client:idle`, except the file it is looking for changes to referencing onLoad in `load.ts` or `onIdle` in `idle.ts`. I noticed if I click through on the link for `visible.ts`. I get this error:
```
Could not load content for http://localhost:3000/node_modules/astro/src/runtime/client/visible.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```
This 404 is also logged by the dev server:
```
08:11 PM [astro] 404 /node_modules/astro/src/runtime/client/visible.ts 0ms
```

I can confirm there is no file path for `node_modules/astro/src/runtime/client/visible.ts`; I did notice there is a file path for `node_modules/astro/dist/runtime/client/visible.js` if that makes any difference.

The JavaScript works intermittently for like others have reported.

**Comment by jsdevtom** [comment]
I am also experiencing this bug. I can't determine what causes the JavaScript to work and vice versa.

**Comment by jimutt** [comment]
I'm also still experiencing these issues, and the original reproduction from @JosNun still consistently reproduces the issue upon refreshs. @jonathantneal is there anything we can do to have this reopened for further investigation? Is there any additional useful information that we can provide other than what @JosNun & @jadonn have reported? 🙂

**Comment by jonathantneal** [comment]
Thanks for the ping, @jimutt, @boehs, @JosNun, @jsdevtom, @jadonn. Let’s reopen this to investigate further.

**Comment by jsdevtom** [comment]
I'm not sure of the original cause, but hopefully this can shed some light on the matter:

On the initial load, the HTML looks like this:
![html-initial](https://user-images.githubusercontent.com/17221813/151706871-59481999-efbe-49d7-9042-1e4132427b38.png)

And the debugger looks like this:
![debugger-initial](https://user-images.githubusercontent.com/17221813/151706879-600d2d3a-18dc-4089-a51f-c5b72eabe5a9.png)

The `astroId` matches.

After reloading the page, the `astroId` in the HTML changes:
![html-after-reload](https://user-images.githubusercontent.com/17221813/151706934-287469a6-8050-481b-8784-f37a1415e350.png)

but the `astroId` in `node_modules/astro/dist/runtime/client/load.js` stays the same.
![debugger-after-reload](https://user-images.githubusercontent.com/17221813/151706940-8de4840e-196b-4b04-a59c-afb258a167f8.png)

This causes `roots[0]` to be undefined and thus the error:
> `Cannot read properties of undefined (reading 'querySelector')`

**Comment by jsdevtom** [comment]
@jonathantneal does my post help at all? Do you have any ideas what could be the root cause?

**Comment by matthewp** [comment]
I'm looking into this.

**Comment by matthewp** [comment]
This works if you use the `--experimental-static-build` flag. I'll look into why its failing without the flag, but for people here can you possibly use that?

**Comment by matthewp** [comment]
The underlying issue is in how Vite creates these external modules for inline scripts and then invalidates them (in this case it doesn't). This would be difficult to fix, so I propose we consider this fixed behind the flag (which will go stable soon).
