### ISSUE TITLE
🐛 BUG: Style Issues when using `@apply` (TailwindCSS)

### ISSUE THREAD

**Issue by SlicedSilver** [withastro/astro#2660]
### What version of `astro` are you using?

0.23.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I've come across potentially two unexpected behaviours when using TailwindCSS with Astro 🚀:

1. When using CSS modules (in my case with Preact components), the first development preview (`npm run dev`) won't have the styles from the CSS modules included on the page. However, triggering a HMR refresh will result in the styles appearing correctly. I think this issue may only occur in conjunction with the issue below (using `@apply`).
2. When using `@apply` from tailwind within any stylesheet (inline on page, or within a CSS module), the development preview will work correctly (after the first refresh as above) however when building the project then those styles and any other styles for that page will not be bundled correctly. 

The first issue can be resolved by removing TailwindCSS. Commenting out the tailwind section of the `postcss.config.js` will result in the styles from the CSS module appearing on the first development preview.

The second issue can be worked around by not using any `@apply` directives within any of the styles. Likewise, removing tailwind from the project will result in the styles being correctly built and bundled even if there is an `@apply` within the styles. In that case the `@apply` will end up in the final css which wouldn't be valid CSS but at least the rest of the styles are included correctly.

### Reproduce: `@apply` issue with builds
1. Open the stackblitz example, and stop the dev server.
2. Build the project: `npm run build`.
3. Within the `dist` folder, notice that the bundled styles doesn't include the classes from the two CSS modules. We can search for the classes: `test-style`& `test-style-two` and confirm that they are missing.
4. Go to `src/components/SimpleTwo/SimpleTwo.module.css` file and replace `@apply text-orange-500;` with `color: orangered;`.
5. Run the build again, notice that the bundled styles now includes the previously missing classes (search for `test-style`).

### Reproduce: Initial Development Preview Issue
* Probably only occurs when one of the files has an `@apply` present.
1. Open the stackbiltz example, notice that all the text on the screen is black (no styles applied).
2. Trigger a HMR refresh, for example add some whitespace to a css file and press save, and notice that the text will now be styled.
3. Stop the dev server.
4. Comment out the tailwind section of the `postcss.config.js` file.
5. Start the preview: `npm run dev`.
6. Notice that the plain CSS module works correctly now on the first load (blue text).

### Additional Notes
I have noticed in a larger project that if the build process determines that a css module doesn't need to be bundled (with anything else) then it will correctly generate the css file (for example `MyComponent.123abc.css`) even if it had `@apply` but it won't include the link tag in the generated html file.

Essentially, using `@apply` generally works correctly while developing but breaks when building the site. Avoiding the use of `@apply` is a reasonable solution to the problem, however it would be nice to use if possible.

Thanks for the awesome project.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nlrrmf?file=src%2Fcomponents%2FSimpleTwo%2FSimpleTwo.module.css

**Comment by tony-sull** [comment]
I just ran into this one as well.  Turns out it isn't actually specific to `@apply`, it looks like the issue may be related to the module graph tracking dependency graphs in `.astro` files

It looks like there may be a bit of a synchronization issue that got worse in 0.23.1.  In this [repro based on with-tailwindcss](https://stackblitz.com/edit/github-yovedu), I tracked it as far as Astro's [renderer (here)](https://github.com/withastro/astro/blob/8343ff6fb54dbb9d43d8c9f4d7c0c1cf4cfae342/packages/astro/src/core/render/dev/css.ts#L27)

## **With 0.23.2**
Tailwind styles aren't included on the page on first load, or reload.  They're only compiled and included when the actual `global.css` file is saved triggering HMR

Logging from [getStylesForURL](https://github.com/withastro/astro/blob/8343ff6fb54dbb9d43d8c9f4d7c0c1cf4cfae342/packages/astro/src/core/render/dev/css.ts#L27), the module graph doesn't show any dependencies for `pages/index.astro` until the file is saved again to trigger a rebuild.  Any updates to `layouts/Base.astro` and `styles/global.css` are ignored until the page's module graph is fixed on a page rebuild

## **With 0.23.0**
Tailwind styles aren't included on first page load, but do seem to be getting built in the background.  Refreshing the browser picks up the built tailwind styles and HMR starts working

Logging from [getStylesForURL](https://github.com/withastro/astro/blob/8343ff6fb54dbb9d43d8c9f4d7c0c1cf4cfae342/packages/astro/src/core/render/dev/css.ts#L27), the module graph doesn't show any dependencies for `pages/index.astro` on the initial page request.  Refreshing the browser without changing/saving any source files does catch up though, it now shows module dependencies and HMR is working

---

I haven't managed to track down which change in `0.23.1` is part of this one, but hopefully we can actually track down the initially unstyled behavior in 0.23.0 at the same time :+1:

**Comment by natemoo-re** [comment]
@tony-sull One HMR problem is fixed by https://github.com/withastro/astro/pull/2681, but the underlying issue with Vite not populating the module graph seems to remain.

**Comment by songololo** [comment]
I'm also running into this on all recent versions including today's `0.23.4`.

Only thing that seems to work is to move the styles inline, which becomes difficult for more complex CSS situations...

**Comment by songololo** [comment]
Another update:

Using `astro@next` fixes the problem for me.

Ironically, it also break dev mode... so for now developing with v23 and building with v24 🤷

**Comment by FredKSchott** [comment]
These issues should be resolved as of Astro v0.24.0. Be sure to follow our updated Tailwind docs if you run into trouble: https://docs.astro.build/en/guides/styling/#-tailwind

**Comment by songololo** [comment]
@FredKSchott thanks for the release. FYI that the builds are definitely working now though I've noticed that in dev mode the home page sometimes still doesn't load tailwind styles (though non-home pages do seem to work). Sometimes the homepage will randomly start working. If I can figure out rhyme or reason I'll open a new issue.

**Comment by Sergix** [comment]
> I'm having a hard time pinning down the issue in my case.
> 
> I have the issue both when in dev and when building, though things seem to be worse for build.
> 
> `@apply` seems to work from the home `.astro` file.
> 
> But `@apply` is not working when used from a `vue` component loaded from the home page.
> 
> Yet, those same components work fine (and CSS loads fine) when loaded via non-home pages.
> 
> Inlining the CSS solves the problem, but can make the template `html` very verbose and is something I'd like to avoid if at all possible.
> 
> UPDATE In my own case, the above basically stems from links to the `vue` scoped styles being omitted from the homepage `html` for some reason (but is present on the non-home page `html`).

The issue is possibly related to [how Vue processes component styles.](https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css) The recommended fix when using `@apply` is to use [Tailwind's plugin system](https://tailwindcss.com/docs/plugins) instead of having a global css file with `@layer` directives. [As stated in Tailwind's documentation](https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css):
> Honestly though the best solution is to just not do weird stuff [using `@apply` with per-component styles] like this at all. Use Tailwind’s utilities directly in your markup the way they are intended to be used, and don’t abuse the @apply feature to do things like this and you will have a much better experience.
