### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Abhi13027** [withastro/astro#2984]
### What version of `astro` are you using?

0.26.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Error: Missing "./server.js" export in "react-dom" package. Can't submit any code related to the issue as of now. It is company's policy

### Link to Minimal Reproducible Example

https://i.postimg.cc/1tq37RwW/Screenshot-2022-04-04-at-7-02-01-PM.png

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
make sure that you update all of your integrations, this is an issue fixed in the latest version of `@astro/react`

**Comment by joeldbirch** [comment]
I'm still getting this with a fresh install with the `docs` template. Same specs as OP. Tried `npm install -D @astrojs/react@latest` as suggested by @FredKSchott but its version didn't change (^1.0.0).

**Comment by bluwy** [comment]
@joeldbirch it seems to be working fine for me. Make sure you setup the template with `npm create astro@latest` too, perhaps you got an older version.

**Comment by joeldbirch** [comment]
Thank you. It did indeed install later versions when I tried a fresh install (astro@1.1.1 for example), which worked. It seems I also had to delete my node_modules folder in my Lerna workspace, which was a variable I didn't mention. Anyway, all good, and thanks for your help @bluwy.

**Comment by ianstormtaylor** [comment]
I'm getting this same error with a completely fresh install of the Astro `docs` template. I've deleted all `node_modules` and re-installed and nothing changes… why is it happening on a fresh install?
