### ISSUE TITLE
🐛 BUG: CSS modules not bundled in built sites if using client:only vue components imported via alias 

### ISSUE THREAD

**Issue by songololo** [withastro/astro#3199]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

## CSS modules not bundled when building sites if using `client:only` vue components imported via alias

This is a similar issue to existing (closed) issues where CSS modules imported to `client:only` `vue` (or other) components are ignored when building a site:
- https://github.com/withastro/astro/pull/3113
- https://github.com/withastro/astro/issues/2966
- https://github.com/withastro/astro/issues/2225

These issues are now resolved and closed, however, the issue still arises when importing a component via an alias.

For example:
- It works when using `import Counter from '../components/Counter.vue';`
- But not when using `import Counter from '@src/components/Counter.vue';`

Note - this issue is not a problem in development mode, so you have to build then preview the site to see the problem in action.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fwoavp-wvrbax

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pmochine** [comment]
Probably related to https://github.com/withastro/astro/issues/2575 as well

**Comment by jasikpark** [comment]
I'm having the same problem w/ `<Carousel client:only/>` in React when `Carousel.tsx` imports CSS - it seems that since only the astro root is added and none of the other assets, the CSS doesn't get included in the bundle. The dev server works fine for it though.

**Comment by FredKSchott** [comment]
I can confirm on the latest v1.0.0-beta as well. This is only `client:only`, and not any other `client:*` that I tested.

**Comment by matthewp** [comment]
This is caused by an upstream bug: https://github.com/rollup/plugins/issues/1190. Tracking that and can follow-up when it's complete.

**Comment by matthewp** [comment]
Appears to still be happening: https://stackblitz.com/edit/github-fwoavp-hrx2y2?file=package.json

**Comment by matthewp** [comment]
@bluwy this might be fixed by that new resolution idea we discussed. Assigning to you, but this can be checked *after* the refactor.

**Comment by bluwy** [comment]
Looks like this is fixed in Astro 1.2.0, https://github.com/withastro/astro/pull/4699

**Comment by stefanullinger** [comment]
I am still seeing a similar issue in Astro 1.6.0 and @astrojs/react 1.2.2. After deploying to Vercel the components are displayed unstyled in the browser.

**Comment by joechipjoechip** [comment]
Using version 4.0.6 and the issue is still there .. :/
