### ISSUE TITLE
🐛 BUG: Dynamic import fails with paths unknown at compile time for astro build

### ISSUE THREAD

**Issue by cpetrov** [withastro/astro#3373]
### What version of `astro` are you using?

1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using a dynamic import (`await import(...)`) with paths that are unknown at compile time fails for `astro build` but works for `astro start`.

```astro
---
const teideImg = (await import('../images/teide.jpg')).default
---
<img src={teideImg} />
```

... works in all cases (https://codesandbox.io/s/bold-tesla-ihmnuh), while:

```astro
---
function getImagePath() {
  return '../images/teide.jpg';
}
const teideImg = (await import(getImagePath())).default
---
<img src={teideImg} />
```
... fails for `astro build` with `Cannot find module '/sandbox/images/teide.jpg' imported from /sandbox/dist/entry.mjs` (https://codesandbox.io/s/loving-bhaskara-el5c9e) but works for `astro dev` (https://codesandbox.io/s/intelligent-lucy-lpzief).

### Link to Minimal Reproducible Example

https://codesandbox.io/s/loving-bhaskara-el5c9e

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I believe this is a known limitation, but I'll make sure to confirm this with the rest of the core team. We definitely need to disable this or warn during dev if we can't make it work in build.

Internally, I'm fairly certain that Vite is only able to scan dynamic imports using string literals or occasionally dynamic strings using [`@rollup/plugin-dynamic-import-vars`](https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars), but something fully dynamic like a function call won't work.

One potential workaround is to use Vite's [`import.meta.glob()`](https://vitejs.dev/guide/features.html#glob-import) feature to ensure everything in your `../images/` directory is available in this file. This should allow you to dynamically reference a filepath constructed at runtime, provided it exists.

**Comment by natemoo-re** [comment]
Action item from Community Call
- Looks like Vite has a built-in warning for this! We seem to be swallowing it, but shouldn't be.
- We want to remove any differences between dev and build if possible, this is a larger ongoing task.

**Comment by simonwiles** [comment]
See also #2647.  It's especially frustrating when you have everything working really nicely in `dev` and it won't build...

**Comment by jaycedotbin** [comment]
I had this issue when using `<Picture/>` and `<Image/>` component also, a workaround that I did was to check if I was on dev or prod and doing inline imports, not the prettiest solution but it worked for me

```astro
  <Picture src={import.meta.env.MODE === "production" ? post.frontmatter.image_url : import("../" + post.frontmatter.image_url)} alt={post.frontmatter.image_alt} widths={[1280, 1920]} sizes="(max-width: 800px), 100vw, 800px" aspectRatio="16:9" />
```

**Comment by ChristineTham** [comment]
I had to resort to this really ugly hack ....

```
---
import { Image } from '@astrojs/image/components'

export interface Props {
  image?: string
}

const { image } = Astro.props as Props

const defaultImage = '../images/default.png'
const images = import.meta.glob('../images/*/*')
const imagesrc = await images[image || defaultImage]() as Record<string,any>
---
<Image  src={imagesrc.default} />
```

**Comment by obennaci** [comment]
Using Vite's `import.meta.glob` works. I guess the snippet/typing could be improved a little with:

```astro
---
// ...
const images = import.meta.glob<ImageMetadata>('../images/*/*', { import: 'default'})
const imagesrc = await images[image || defaultImage]()
---
<Image src={imagesrc} />
```

**Comment by bluwy** [comment]
Looks like the reason the warning isn't reported by Vite is because it only reports for non-ssr transforms, in which case we're running in SSR instead. I feel like it's still worth providing a warning in SSR regardless, so I'll test out this change in Vite.

**Comment by ChristineTham** [comment]
> Using Vite's `import.meta.glob` works. I guess the snippet/typing could be improved a little with:
> 
> ```astro
> ---
> // ...
> const images = import.meta.glob<ImageMetadata>('../images/*/*', { import: 'default' })
> const imagesrc = await images[image || defaultImage]()
> ---
> <Image src={imagesrc} />
> ```

Thanks - that is slightly cleaner and avoids the ugly typecast. Although I still had to manually specify a typecast to `ImageMetadata` otherwise I get a warning

```typescript
const images = import.meta.glob('../images/**/*', { import: 'default' })
const image = await images[src || defaultImage]() as ImageMetadata
```

**Comment by bluwy** [comment]
This should be fixed upstream in Vite 3.0.9 which the latest Astro version uses. It will now warn when the import can't be resolved in dev mode as it needs to be static in order for Vite to "link" it.

**Comment by jtomek** [comment]
Vite import has certain [limitations](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations). One of them is that that dynamic imports must end with a file extension.


```astro
<Image
  src={import(`../data/partners/${logoName}.png`)}
/>
```

Try passing only a variable without its extension. That worked for me. GL.

**Comment by ciokan** [comment]
> Vite import has certain [limitations](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations). One of them is that that dynamic imports must end with a file extension.
> 
> ```astro
> <Image
>   src={import(`../data/partners/${logoName}.png`)}
> />
> ```
> 
> Try passing only a variable without its extension. That worked for me. GL.

Still doesn't work in the frontmatter/component script part of the astro file. It is passed to `getPicture` though:

```
        features.features.map((feature, index) => {
		promises.push(
			getPicture({
				src: import(
					`../static/images/screenshots/${feature.identifier}.png`
				),
				widths: sizes,
				aspectRatio: 1400 / 947,
				formats: ["png"],
			}).then((picture) => {
				pictures[feature.identifier] = picture;
			})
		);
	});
```

**Comment by jtomek** [comment]
What's the error message?

**Comment by MejanH** [comment]
> > Vite import has certain [limitations](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations). One of them is that that dynamic imports must end with a file extension.
> > ```astro
> > <Image
> >   src={import(`../data/partners/${logoName}.png`)}
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Try passing only a variable without its extension. That worked for me. GL.
> 
> Still doesn't work in the frontmatter/component script part of the astro file. It is passed to `getPicture` though:
> 
> ```
>         features.features.map((feature, index) => {
> 		promises.push(
> 			getPicture({
> 				src: import(
> 					`../static/images/screenshots/${feature.identifier}.png`
> 				),
> 				widths: sizes,
> 				aspectRatio: 1400 / 947,
> 				formats: ["png"],
> 			}).then((picture) => {
> 				pictures[feature.identifier] = picture;
> 			})
> 		);
> 	});
> ```

@ciokan , if you `console.log` the value you will get something like this.
```js
{
  default: {
    src: '/@astroimage/file/location/file.ext',
    width: 1200,
    height: 801,
    format: 'jpg'
  },
  [Symbol(Symbol.toStringTag)]: 'Module'
}
```
you have to use default import such as `const coverImgSrc = (await import(`../../folder/${variable}`)).default as any`. 

More info in here https://vitejs.dev/guide/features.html#dynamic-import

**Comment by fubits1** [comment]
Maybe helpful to whomever lands here: As a workaround (working with Astro 2.0) I wrote a utility function to satisfy Vite's explicit extension requirement. Receive filename, extract extension, return dynamic import with explicit extension. Can confirm that this works with a plain Astro (2.0) component with 15 images.

```
import path from "path";
function dynamicViteAssetImport(imageFileName) {
  const filename = path.parse(imageFileName);
  const name = filename.name;
  const ext = filename.ext;
  switch (ext) {
    case ".webp":
      return import(`../assets/${name}.webp`);
    case ".jpg":
      return import(`../assets/${name}.jpg`);
    case ".png":
      return import(`../assets/${name}.png`);
    case ".svg":
      return import(`../assets/${name}.svg`);
    case ".gif":
      return import(`../assets/${name}.gif`);
    case ".avif":
      return import(`../assets/${name}.avif`);
    case ".jpeg":
      return import(`../assets/${name}.jpeg`);
    default:
      return import(`../assets/${name}.jpg`);
  }
}

```

Consume with:
```
 <Image src={dynamicViteAssetImport(imageFileName)}  />
```

**Comment by kireerik** [comment]
Maybe it would make sense to improve the current warning by adding something like this to it as well:
```Markdown
It may not work as expected during (Astro) `build`.
```
&nbsp;
Full example:
```Markdown
The above dynamic import cannot be analyzed by Vite. It may not work as expected during (Astro) `build`.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
```
&nbsp;
Current warning:
```Markdown
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
```

**Comment by modulareverything** [comment]
I'm seeing this issue myself on a "page builder" componet I have. It works fine in development, but I get this error in production:

```
src/utils/block-types.tsx:2:31 - error TS2307: Cannot find module '../components/BookADemoCTA.astro' or its corresponding type declarations.

2   bookADemoCTA: (await import('../components/BookADemoCTA.astro')).default,

...etc...
```

Here's the code for the block builder:

```tsx
const blockTypeImports: Record<string, () => Promise<any>> = {
  bookADemoCTA: () => import('../components/BookADemoCTA.astro'),
  awards: () => import('../components/Awards.astro'),
  bookDemoInput: () => import('../components/BookADemoInput.astro'),
  calloutCards: () => import('../components/CalloutCards.astro'),
  caseStudiesSlider: () => import('../components/CaseStudiesSlider.astro'),
  containedImage: () => import('../components/ContainedImage.astro'),
  cssMarquee: () => import('../components/CSSMarquee.astro'),
  featuresCards: () => import('../components/FeaturesCards.astro'),
  heroContent: () => import('../components/HeroContent.astro'),
  icon: () => import('../components/Icon.astro'),
  largeTitle: () => import('../components/LargeTitle.astro'),
  logosTicker: () => import('../components/LogosTicker.astro'),
  mainContent: () => import('../components/MainContent.astro'),
  reviewsPill: () => import('../components/ReviewsPill.astro'),
  title: () => import('../components/Title.astro'),
};

export const getBlockComponent = async (blockType: string) => {
  const importer = blockTypeImports[blockType];
  if (importer) {
    const module = await importer();
    return module.default;
  }
  return () => (
    <code>
      Unknown block!
      <br />
      {blockType}
    </code>
  );
};
```

and that's consumed by:

```astro
---
        {blocks.map((block: any) => {
          const BlockComponent = getBlockComponent(block._type);
          return <BlockComponent {...block} />;
        })}
---
```

Happy to refactor the `block-types.tsx` to be an Astro file if that would solve it.

I'm trying to avoid importing ALL of the components when only 2–3 may be needed.

**Comment by modulareverything** [comment]
Spent some more time with this and managed to get it working using the `import.meta.glob()` directive.

```tsx
const componentGlobs = import.meta.glob('../components/*.astro');

const blockTypeMap: Record<string, string> = {
  bookADemoCTA: 'BookADemoCTA',
  awards: 'Awards', 
  // etc
};

export const getBlockComponent = async (blockType: string) => {
  const componentName = blockTypeMap[blockType];
  if (componentName) {
    const componentPath = `../components/${componentName}.astro`;
    const componentLoader = componentGlobs[componentPath];
    if (componentLoader) {
      const module = await componentLoader() as { default: any };
      return module.default;
    }
  }
  return () => (
    <code>
      Unknown block!
      <br />
      {blockType}
    </code>
  );
};
```

and then consuming it with:

```tsx
        {await Promise.all(
          blocks.map(async (block: any) => {
            const BlockComponent = await getBlockComponent(block._type);
            return <BlockComponent {...block} />;
          })
        )}
```

Hope this helps someone in the future :)
