### ISSUE TITLE
🐛 BUG: Error when building Just the Basics starter :  `Cannot read properties of undefined (reading 'icon')`

### ISSUE THREAD

**Issue by florian-s-code** [withastro/astro#3473]
### What version of `astro` are you using?

v1.0.0-beta.36

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

The build of "Just the basics" starter fails with the error :  `Cannot read properties of undefined (reading 'icon')`
We have got 2 reports through Discord and I have been able to reproduce it.

Dev mode works, only the build fails.

**Reproduction steps:**

1. Run `npm init astro`
2. Choose "Just the basics" and default options (no integrations)
3. Run `npm run build`

```
❯ npm run build --verbose
[...]

> @example/basics@0.0.1 build
> astro build

11:15:20 [build] Collecting build information...ed in 27ms
11:15:21 [build] Completed in 516ms.load Completed in 27ms
11:15:21 [build] Building entrypoints for prerendering...
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
11:15:21 [build] Completed in 452ms.load Completed in 27ms

 generating static routes 
▶ src/pages/index.astro
 error   Cannot read properties of undefined (reading 'icon')
    at file:///tmp/tmp.SrDkX4sUEP/test/dist/entry.mjs?time=1653902121795:84:21
    at ft (file:///tmp/tmp.SrDkX4sUEP/test/dist/entry.mjs?time=1653902121795:66:398)
    at w (file:///tmp/tmp.SrDkX4sUEP/test/dist/entry.mjs?time=1653902121795:39:4033)
npm timing command:run Completed in 2513ms
npm verb exit 1
npm timing npm Completed in 2646ms
npm verb code 1
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by florian-s-code** [comment]
I have proposed a quick fix for this specific theme so that people starting with `create-astro` and the "_Just the basics_" starter are not led down by a bug on their first build.

It seems to be a structural bug with named slots, that break the build if no content is passed. A better fix is needed.

**Comment by sarah11918** [comment]
I merged #3475 to implement a quick fix, so that the starter builds, but leaving this issue OPEN for @bholmesdev or anyone who wants to implement a different solution.

**Comment by natemoo-re** [comment]
Reopening this since the underlying bug is still a problem. I'm looking into it.

**Comment by matthewp** [comment]
We have a default parameter we use internally for children, something like `function render(.., children = {})` and that is being tree-shaken away. I'm pretty sure it's this Rollup change causing it: https://github.com/rollup/rollup/pull/4498

It was reverted today: https://github.com/rollup/rollup/pull/4520

So going to try again and see if the problem goes away.
