### ISSUE TITLE
Vercel Edge Functions 100% Crash Rate

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/astro#5926]
### What version of `astro` are you using?

2.0.0-beta.3

### Are you using an SSR adapter? If so, which one?

Vercel 3.0.0-beta.1

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Any Vercel Edge functions crash using the latest beta Astro & Vercel adapter versions. This is the error shown in the Vercel logs.
```
[GET] /favicon.ico
15:11:03:32

TypeError: Cannot read properties of undefined (reading 'includes')    at (chunks/astro.cb0af384.mjs:90:5700)    at (entry.mjs:1:0)    at (render:middleware.js:1:17)
```

To reproduce:

1. Create a fresh Astro project
2. `npm i astro@beta @astrojs/vercel@beta`
3. Change the import to use the edge adapter
4. Deploy to Vercel

I've linked a reproduction repo below, which also has a link to a live deployment.

### Link to Minimal Reproducible Example

https://github.com/TheOtterlord/astro-edge

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
What version of Node? The major thing that changed with Vercel in the beta period is dropping Node 14 support.

**Comment by matthewp** [comment]
Thanks, I'm debugging it.

**Comment by space-otter** [comment]
Can confirm the bug. Every new deployment, even older projects and versions, with astro on vercel succeeded but the build is incomplete.

**Comment by matthewp** [comment]
@space-otter is this only on the newest version of the adapter for you? Does it happen on the previous? What version of Node is your Vercel project running? I'm still debugging on my end.

**Comment by matthewp** [comment]
Oh sorry, you said you were on Node 19.

**Comment by space-otter** [comment]
> @space-otter is this only on the newest version of the adapter for you? Does it happen on the previous? What version of Node is your Vercel project running? I'm still debugging on my end.

The error is reproducible for the actual astro beta version, 1.9.2 and 1.9.1. Also only in combination with the vercel adapter.
Weirdly, it didn't happen before today to me and I also didn't changed any dependencies. Different node versions didn't fixed it either.

**Comment by space-otter** [comment]
@matthewp the issue has been resolved with the new release :) 👍

**Comment by matthewp** [comment]
@space-otter oh wow, @TheOtterlord can you confirm on your end as well?

**Comment by matthewp** [comment]
Sorry, do you mean yes you can confirm it's fixed or yes it's still happening? From the screenshot it looks like it's still happening for you. If so I'll update the demo app and continue debugging.

**Comment by TheOtterlord** [comment]
Oh yeah :sweat_smile:
It's still happening

**Comment by space-otter** [comment]
@matthewp could it be that there are some issues on Vercel's side? Strangely I found some issues within the bundle of a project that I deployed last week. Now, I redeployed it and it works fine.

**Comment by space-otter** [comment]
Two otters, the same issue. Its a conspiracy.

**Comment by matthewp** [comment]
Found it.
