### ISSUE TITLE
Style missing when using client:only directive

### ISSUE THREAD

**Issue by timseverien** [withastro/astro#6931]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

## Summary

Given Svelte component with styles used in another Svelte component loaded with the `client:only` directive, styles of the inner component are missing on `astro build`.

## Example

Let’s say we have a component called `Flow` to create vertical rhythm:

```svelte
<div class="flow">
  <slot />
</div>

<style>
  .flow {
    display: flex;
    flex-direction: column;
    gap: 1em;
  }
</style>
```

Additionally, we have a component `Card` that uses `Flow`:

```svelte
<script>
  import Flow from "./Flow.svelte";
</script>

<Flow>
  <div>Header</div>
  <div>Content</div>
  <div>Footer</div>
</Flow>
```

Let’s say we want to use the `Card` component client-side only. In `index.astro`, we write:

```astro
<Card client:only />
```

Everything looks fine, but on production the `Flow` style is missing.

## Distilling the problem

- The problem doesn’t occur on `astro dev`
- The problem does occur when running `astro build && astro preview`
- When the `client:only` directive is removed, the `Flow` styles are applied again
- When the `client:only` directive is swapped for `client:loaded` or any of the other `client:*` directives, styles are applied again
- When adding a `<Flow>` component to the `index.astro`, the styles are applied again, regardless whether we keep the `client:only` directive on `Card` or not

It appears `astro build` performs an action that `astro dev` doesn’t, which may discard styles or cause classname mismatches.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/bug-astro-svelte-styles?file=src/pages/error.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by vampaz** [comment]
Can add that I've the same with Vue. I think it is related with this https://github.com/withastro/astro/commit/7653cf9e9fedc6edc6038603248351e276191c3a

**Comment by amxmln** [comment]
I can confirm this is an issue with Vue as well. Maybe it has to do with scoped styles?

Another thing I noticed, that may be of relevance is that the ordering of styles is different in dev and build. Importing `normalize.css` causes the styles from normalize to override my styles during dev, because it gets added *after* my styles, but everything is fine after build.

This started roughly around the same time the component styles disappeared when using `client:only`.

**Comment by josephmcg** [comment]
I run into the same issue with Vue as well

**Comment by saxoncameron** [comment]
Any update on this one? Running Vue and have the same issue

**Comment by tonyski** [comment]
same issue with Vue

**Comment by TUBB** [comment]
same issue with Vue

**Comment by bluwy** [comment]
Sorry for the regression. I've looked into the issue and #7218 should fix it.

**Comment by Chudroy** [comment]
Still got this problem with astro 2.10.15

**Comment by onurusluca** [comment]
Still having the problem with Astro(also with Starlight), Vue and PrimeVue.

**Comment by joechipjoechip** [comment]
Still have the issue with version 4.0.6 .. :/

**Comment by Fasa2509** [comment]
Same here but using Preact

**Comment by chowdud** [comment]
Getting the same with version 4.2.4 - specifically pertaining to loading in a stylised datatable, it momentarily renders in correctly, only then to have the styles removed completely.

**Comment by undead404** [comment]
This issue should probably not be closed. Got the same problem (styles, from an SCSS module, disappear after build but present in dev) with 4.2.5

**Comment by M-erb** [comment]
This is still an issue in 4.9.1 using vue. All styles load correctly from the vue component in dev mode, but as soon as I build it the styles no longer load
