### ISSUE TITLE
Injected Routes are not being pre-rendered in hybrid mode.

### ISSUE THREAD

**Issue by tgerstle** [withastro/astro#7721]
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When output is set to hybrid and routes are injected using an adapter, the injected routes are not pre-rendered. The routes are pre-rendered if no output is set. If the output is set to server and export const prerender = true is set in the frontmatter, the route still is not prerendered.

### What's the expected result?

I expect injected routes to pre-render by default in hybrid mode. An alternative could be to ensure the front matter "prerender" variable works normally on injected routes or perhaps add a configuration on the injected routes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-ccvkpy?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I believe `injectRoute({ entryPoint: "value", prerender: true })`  should work. I don't see this in the docs, though! We'll need to update that.

**Comment by natemoo-re** [comment]
Hmm, odd. When using `entryPoint: './src/site/demo/index.astro'`, I am seeing the behavior you mentioned. But when using `entryPoint: 'src/site/demo/index.astro'`, all the metadata seems correct and the page _is_ prerendered. Seems like a bug on our end!

**Comment by natemoo-re** [comment]
Some more context from @delucis here on a similar issue. https://github.com/withastro/astro/issues/7642#issuecomment-1636122915

This seems like a poor API design choice on our end, I would expect both formats to work in this case.

**Comment by delucis** [comment]
I'm surprised `entryPoint: 'src/site/demo/index.astro'` works at all! In my testing it didn't previously (which kind of makes sense, because we support resolving an npm module here, so `src` should be the `src` npm package).

**Comment by natemoo-re** [comment]
Still seeing an issue with `entryPoint: './src/site/demo/index.astro'` after all the recent fixes, so keeping this open.

**Comment by rishi-raj-jain** [comment]
Is this still an issue with Astro 3?

**Comment by lilnasy** [comment]
- `entryPoint: 'src/site/demo/index.astro'` gets prerendered by default since #7986
- `entryPoint: 'src/site/pages/nested/index.astro'` is no longer broken since 3.0

The bugs themselves are fixed but a test could be added before this issue closes.

**Comment by Fryuni** [comment]
This issue is still happening for `.ts` routes.

`.astro` routes are being prerendered fine, even mixing prerendered and SSR routes are working, but this only gets prerendered with `output: 'static'`:

```ts
injectRoute({
  pattern: '/[...path]',
  entrypoint: 'mypackage/route.ts',
  prerender: true,
});
```

**Comment by natemoo-re** [comment]
Sorry for the lack of updates here! Confirming that this is definitely still an issue. I'll make sure this gets back on our TODO list.

**Comment by nadar** [comment]
@natemoo-re @Fryuni  I am far away from an astro expert (but we like it so far! 😄), but we are trying to create integrations which can be distributed over npm (obviously). We have detected that when we use `injectRoute()` in `astro:config:setup` hook there is no possibility to provide an endpoint file via an NPM package which will be correctly resolved into the node_modules folder. Even the docs state we should use `@npmpackage/.../foobar.ts` (in the middleware section at least => https://docs.astro.build/en/reference/integrations-reference/#addmiddleware-option) it will not be resolved correctly. So we tested all those cases and nothing works:

```js
injectRoute({
  pattern: '/sitemap.xml',
  entrypoint: '@flyo/nitro-astro/sitemap.js'
})
```

```js
injectRoute({
  pattern: '/sitemap.xml',
  entrypoint: 'sitemap.js'
})
```

```js
injectRoute({
  pattern: '/sitemap.xml',
  entrypoint: './sitemap.js'
})
```

Does this issue confirm my bug?

**Comment by Fryuni** [comment]
@nadar Two key issues there:
- The pattern should not start with `/`. Look at how [Starlight does it](https://github.com/withastro/starlight/blob/b13b4624b50e1c28cc2255664e772c82f2604f99/packages/starlight/index.ts#L42-L49).
- The entrypoint is an import path, not a file path. I think the one in your first snippet should work since ESM imports should resolve to the file when it is explicit. Test changing just the pattern.

  If changing just the pattern doesn't work, try explicitly exporting them from your package
  [This is how Starlight does that](https://github.com/withastro/starlight/blob/b13b4624b50e1c28cc2255664e772c82f2604f99/packages/starlight/package.json#L161-L162) for reference.
  So you can try adding `"./sitemap": "./sitemap.js"` [here](https://github.com/flyocloud/nitro-astro/blob/20759f900fcad3ab6890e338029fed330658659c/package.json#L7-L28) and use this:
  ```ts
  injectRoute({
    pattern: 'sitemap.xml',
    entrypoint: '@flyo/nitro-astro/sitemap'
  });
  ```

**Comment by nadar** [comment]
Thank you so much @Fryuni it works! Should i send a PR for improve the documentations? So everyone struggling on this could profit from your generous answer.

1. i have added ` "./sitemap.js": "./sitemap.js"` to export defintion of package.json
2. defined the entrypoint as followed `entrypoint: '@flyo/nitro-astro/sitemap.js'`

**Comment by ematipico** [comment]
I will look into this issue.

**Comment by ematipico** [comment]
Closing the issue. I tested the reproduction with the latest Astro, and both injected routes are correctly pre-rendered.
