### ISSUE TITLE
@astrojs/vercel with edge function target doesn't render 404.astro page

### ISSUE THREAD

**Issue by susickypavel** [withastro/astro#7735]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac, Windows

### What browser are you using?

Chrome, Firefox, Safari

### Describe the Bug

Deployed app: https://astro-vercel-404-edge-bug.vercel.app/
Code: https://stackblitz.com/edit/github-z7x12r?file=src%2Fpages%2F404.astro

Astro website deployed on Vercel using edge adapter doesn't recognize 404.astro page and browser native 404 page is shown instead.

It works in development, it doesn't work on Vercel only. It doesn't matter whether the 404.astro is prerendered or not.

### What's the expected result?

Navigating to a page that doesn't exist shows the content of 404.astro.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-z7x12r?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alanescarcha** [comment]
Bump!
It seems that in 2.8.0 it worked correctly.

**Comment by sahilsuman933** [comment]
@susickypavel, I believe this issue has been resolved in one of the latest PRs. If you visit https://gullible-galaxy.vercel.app/, you can see that the 404 page is rendering correctly.

**Comment by susickypavel** [comment]
> @susickypavel, I believe this issue has been resolved in one of the latest PRs. If you visit https://gullible-galaxy.vercel.app/, you can see that the 404 page is rendering correctly.

Can you provide stackblitz project? I'm running the latest version of Vercel adapter and Astro and still seeing this issue.

**Comment by sahilsuman933** [comment]
I am also experiencing the same issue in the latest version of Astro. However, I have not encountered any problems when linking to the Astro repository using "pnpm link astro" with all the latest pull requests merged. Therefore, please wait for the latest release, as it will address the issue. @susickypavel 

// @Princesseuh  Just to confirm again, can you test that from your end?

**Comment by matthewp** [comment]
We have deprecated the Vercel Edge and Netlify Edge adapters due to compatibility issues and are encouraging people to instead use the serverless versions of these adapters, along with Edge Middleware, which we feel gives you the best of both worlds. Our adapter migration plan is laid out in this [roadmap issue](https://github.com/withastro/roadmap/discussions/631).

If you're still interested in deploying to these edge platforms I'd encourage you to build an adapter for it. You can use the edge adapter code as a starting point.

Closing as we are not planning on fixing edge adapter bugs (but will continue to support edge middleware).
