### ISSUE TITLE
Returning a new Response with the Status Code 404 causes an Redirect to the (missing) /404.astro Page

### ISSUE THREAD

**Issue by gitcaduff** [withastro/astro#8100]
### What version of `astro` are you using?

2.10.9

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

In the past, with an older version of Astro, it was feasible to generate Responses bearing the 404 status code. However, in the current setup (2.10.9), this process triggers an infinite loop due to Astro's subsequent search for the missing /404.astro page. To circumvent this loop, I opt not to furnish a /404.astro page. This choice stems from my desire to refrain from redirecting users to a dedicated 404 page. Instead, I intend to furnish a 404 Code directly while retaining the requested URL's context.

```
return new Response("custom 404 html content", {
   status: 404
});
```

### What's the expected result?

I would expect to be able to return any page with a 404 code.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-6pmtt6?file=response-with-404-code%2Fsrc%2Fpages%2F[...path].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
@gitcaduff Could not reproduce the issue. The custom 404 response gets served.

Could you check?

![screenshot](https://github.com/withastro/astro/assets/69170106/bf14d0c2-51b0-41cb-8969-07c1c7368f28)

**Comment by gitcaduff** [comment]
Hi @lilnasy, thanks for your ultrafast reply!
I did just check it. It works as expected with "astro preview" but fails with "astro dev".

**Comment by gitcaduff** [comment]
@lilnasy it seems that the problem got back with Astro 4.5.x
if we run "astro dev" Astro tries to find the 404.astro, that does not exist. The result: an infinite loop.
thx

**Comment by lilnasy** [comment]
Could you open a new issue with a small reproduction project that runs into the loop?

**Comment by gitcaduff** [comment]
> @lilnasy it seems that the problem got back with Astro 4.5.x if we run "astro dev" Astro tries to find the 404.astro, that does not exist. The result: an infinite loop. thx

here we go: https://stackblitz.com/edit/stackblitz-starters-jcjvxf?file=response-with-404-code%2Fsrc%2Fpages%2F[...path].astro

**Comment by gitcaduff** [comment]
> Could you open a new issue with a small reproduction project that runs into the loop?

Done: https://github.com/withastro/astro/issues/10581

**Comment by kyr0** [comment]
This almost killed my whole Firebase budget, as a `verifyToken` call is done for the JWT token in my middleware. It still seems to happen in `4.5.17` or is a regression?  Definitely not fixed. I have no static 404 page route. My middleware simply is doing this now, after I removed every of my code, step-by-step, and after countless of debugging hours, believing that the issue is caused somewhere by my code, test code etc., it's still happening with the most simple setup:

```ts
export const onRequest: MiddlewareHandler = async (
  { request },
  next,
): Promise<Response> => {
  // pre-flight request
  if (request.method === "OPTIONS") {
    console.log("Middleware allowed pre-flight request, 200 OK");
    return new Response(null, { status: 200 });
  }

  try {

    console.log("Middleware blocked request with no valid auth");
    return new Response("Not found", { status: 404 });
  } catch (error) {
    console.log("Middleware error", error.message, error.stack);
    logException(error);
    return new Response("Internal Server Error", { status: 500 });
  }
};

```

Once I access  http://localhost:4321/, it's over:

```
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 1ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
Middleware blocked request with no valid auth 2
01:29:10 [404] / 0ms
^C
```

**Comment by kyr0** [comment]
Btw there is no way now to return any `404`, it always ends up in an infinite loop, even if I create a static 404 page. I'm now forced to diverge from security best practices and return a `403` instead. This way there is no endless loop.

**Comment by lilnasy** [comment]
@kyr0 The issue is a systematic one, explained in-depth here: https://discord.com/channels/966563199744872518/1169301147320860772/1227403325083877396.

There are likely multiple manifestations of it still in the codebase. It seems like middleware returning 404 responses is still problematic.

Could you open a new issue for it?

**Comment by kyr0** [comment]
@lilnasy Ah, now I found your comment here - sry; pls. ignore my extra text in the other issue about this being the case still #10735
